"""Add multi-tenancy

Revision ID: bbc0dbe98fa9
Revises: d7b9e1f2a3c4
Create Date: 2026-09-18 09:33:30.490623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc0dbe98fa9'
down_revision: Union[str, Sequence[str], None] = 'd7b9e1f2a3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('ai_risk_alerts', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'ai_risk_alerts', 'companies', ['company_id'], ['id'])
    op.add_column('brands', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.drop_constraint(op.f('brands_name_key'), 'brands', type_='unique')
    op.create_index('idx_brand_company_name', 'brands', ['company_id', 'name'], unique=True)
    op.create_foreign_key(None, 'brands', 'companies', ['company_id'], ['id'])
    op.add_column('categories', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_index('idx_category_company_name', 'categories', ['company_id', 'name'], unique=True)
    op.create_foreign_key(None, 'categories', 'companies', ['company_id'], ['id'])
    op.add_column('demand_history', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'demand_history', 'companies', ['company_id'], ['id'])
    op.add_column('employees', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'employees', 'companies', ['company_id'], ['id'])
    op.add_column('forecast_history', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'forecast_history', 'companies', ['company_id'], ['id'])
    op.add_column('goods_received', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'goods_received', 'companies', ['company_id'], ['id'])
    op.add_column('inventory', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'inventory', 'companies', ['company_id'], ['id'])
    op.add_column('inventory_movements', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'inventory_movements', 'companies', ['company_id'], ['id'])
    op.add_column('products', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.drop_index(op.f('idx_product_sku'), table_name='products')
    op.drop_constraint(op.f('products_barcode_key'), 'products', type_='unique')
    op.drop_constraint(op.f('products_sku_key'), 'products', type_='unique')
    op.create_index('idx_product_company_sku', 'products', ['company_id', 'sku'], unique=True)
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'])
    op.add_column('purchase_order_items', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'purchase_order_items', 'companies', ['company_id'], ['id'])
    op.add_column('purchase_orders', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'purchase_orders', 'companies', ['company_id'], ['id'])
    op.add_column('reorder_decisions', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'reorder_decisions', 'companies', ['company_id'], ['id'])
    op.add_column('returns', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'returns', 'companies', ['company_id'], ['id'])
    op.add_column('sales_order_items', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'sales_order_items', 'companies', ['company_id'], ['id'])
    op.add_column('sales_orders', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'sales_orders', 'companies', ['company_id'], ['id'])
    op.add_column('shipments', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'shipments', 'companies', ['company_id'], ['id'])
    op.add_column('stock_transfers', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'stock_transfers', 'companies', ['company_id'], ['id'])
    op.add_column('supplier_performance', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'supplier_performance', 'companies', ['company_id'], ['id'])
    op.add_column('suppliers', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.drop_constraint(op.f('suppliers_gst_number_key'), 'suppliers', type_='unique')
    op.create_index('idx_supplier_company_gst', 'suppliers', ['company_id', 'gst_number'], unique=True)
    op.create_foreign_key(None, 'suppliers', 'companies', ['company_id'], ['id'])
    op.add_column('users', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.add_column('warehouse_kpi', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'warehouse_kpi', 'companies', ['company_id'], ['id'])
    op.add_column('warehouses', sa.Column('company_id', sa.UUID(as_uuid=False), nullable=True))
    op.drop_constraint(op.f('warehouses_warehouse_code_key'), 'warehouses', type_='unique')
    op.create_index('idx_warehouse_company_code', 'warehouses', ['company_id', 'warehouse_code'], unique=True)
    op.create_foreign_key(None, 'warehouses', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.drop_index('idx_warehouse_company_code', table_name='warehouses')
    op.create_unique_constraint(op.f('warehouses_warehouse_code_key'), 'warehouses', ['warehouse_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('warehouses', 'company_id')
    op.drop_constraint(None, 'warehouse_kpi', type_='foreignkey')
    op.drop_column('warehouse_kpi', 'company_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index('idx_supplier_company_gst', table_name='suppliers')
    op.create_unique_constraint(op.f('suppliers_gst_number_key'), 'suppliers', ['gst_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('suppliers', 'company_id')
    op.drop_constraint(None, 'supplier_performance', type_='foreignkey')
    op.drop_column('supplier_performance', 'company_id')
    op.drop_constraint(None, 'stock_transfers', type_='foreignkey')
    op.drop_column('stock_transfers', 'company_id')
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'company_id')
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_column('sales_orders', 'company_id')
    op.drop_constraint(None, 'sales_order_items', type_='foreignkey')
    op.drop_column('sales_order_items', 'company_id')
    op.drop_constraint(None, 'returns', type_='foreignkey')
    op.drop_column('returns', 'company_id')
    op.drop_constraint(None, 'reorder_decisions', type_='foreignkey')
    op.drop_column('reorder_decisions', 'company_id')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'company_id')
    op.drop_constraint(None, 'purchase_order_items', type_='foreignkey')
    op.drop_column('purchase_order_items', 'company_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index('idx_product_company_sku', table_name='products')
    op.create_unique_constraint(op.f('products_sku_key'), 'products', ['sku'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('products_barcode_key'), 'products', ['barcode'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_product_sku'), 'products', ['sku'], unique=False)
    op.drop_column('products', 'company_id')
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_column('inventory_movements', 'company_id')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'company_id')
    op.drop_constraint(None, 'goods_received', type_='foreignkey')
    op.drop_column('goods_received', 'company_id')
    op.drop_constraint(None, 'forecast_history', type_='foreignkey')
    op.drop_column('forecast_history', 'company_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'company_id')
    op.drop_constraint(None, 'demand_history', type_='foreignkey')
    op.drop_column('demand_history', 'company_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index('idx_category_company_name', table_name='categories')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'company_id')
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.drop_index('idx_brand_company_name', table_name='brands')
    op.create_unique_constraint(op.f('brands_name_key'), 'brands', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('brands', 'company_id')
    op.drop_constraint(None, 'ai_risk_alerts', type_='foreignkey')
    op.drop_column('ai_risk_alerts', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
