"""Add password hash

Revision ID: f2a3cfd8f2bc
Revises: bbc0dbe98fa9
Create Date: 2026-09-18 09:43:00.764866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a3cfd8f2bc'
down_revision: Union[str, Sequence[str], None] = 'bbc0dbe98fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_risk_alerts', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('brands', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('categories', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('demand_history', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('employees', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('forecast_history', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('goods_received', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('inventory', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('inventory_movements', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('products', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('purchase_order_items', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('purchase_orders', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reorder_decisions', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('returns', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sales_order_items', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sales_orders', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('shipments', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('stock_transfers', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('supplier_performance', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('suppliers', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('warehouse_kpi', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('warehouses', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('warehouses', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('warehouse_kpi', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('users', 'password_hash')
    op.alter_column('suppliers', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('supplier_performance', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('stock_transfers', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('shipments', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('sales_orders', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('sales_order_items', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('returns', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reorder_decisions', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('purchase_orders', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('purchase_order_items', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('products', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('inventory_movements', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('inventory', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('goods_received', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('forecast_history', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('employees', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('demand_history', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('categories', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('brands', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ai_risk_alerts', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
