"""
Pydantic V2 schemas for LLM Security Recommendations.
Designed for consumption by BLUF Report Agent, AI Analyst Chat, and Security Dashboards.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, ConfigDict, field_validator


class RecommendationOutput(BaseModel):
    """Structured security recommendation generated by LLM for an attack chain."""
    chain_id: str = Field(..., description="Attack chain identifier (e.g. AC001)")
    immediate_actions: List[str] = Field(
        ...,
        min_length=1,
        description="3-5 urgent actions to take immediately (first 0-60 minutes)",
    )
    containment_actions: List[str] = Field(
        ...,
        min_length=1,
        description="3-5 actions to stop lateral spread and isolate compromised assets",
    )
    investigation_actions: List[str] = Field(
        ...,
        min_length=1,
        description="3-5 actions to perform forensic triage and log deep-dive",
    )
    prevention_actions: List[str] = Field(
        ...,
        min_length=1,
        description="3-5 long-term hardening and posture improvement actions",
    )
    executive_summary: str = Field(
        ...,
        min_length=20,
        description="High-level commander/CISO summary of the threat and recommended posture",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "chain_id": "AC001",
                "immediate_actions": [
                    "Block malicious source IP 192.168.1.50 at perimeter firewall and core routers",
                    "Isolate compromised host 10.0.0.12 from internal network segment",
                    "Revoke active Kerberos and NTLM session tokens for identified administrator accounts",
                ],
                "containment_actions": [
                    "Implement host-based firewall isolation on all endpoints contacted by compromised host",
                    "Enforce strict egress filtering blocking outbound traffic to C2 IPs",
                    "Disable compromised local account and force Active Directory password reset",
                ],
                "investigation_actions": [
                    "Extract memory dump from infected machine to analyze injected DLL payloads",
                    "Review Windows Event ID 4688 and PowerShell ScriptBlock logs (Event ID 4104)",
                    "Query SIEM for beaconing patterns to suspicious external IP addresses",
                ],
                "prevention_actions": [
                    "Deploy Windows Defender Credential Guard to prevent LSASS memory harvesting",
                    "Enforce Multi-Factor Authentication (MFA) on all internal RDP and administrative access",
                    "Update endpoint detection and response (EDR) behavioral blocking rules",
                ],
                "executive_summary": (
                    "A critical multi-stage intrusion was detected initiating with active reconnaissance "
                    "and escalating to credential theft and malware deployment. Immediate network isolation "
                    "and credential revocation are actively required to prevent lateral expansion and data compromise."
                ),
            }
        }
    )


class RecommendationResponse(BaseModel):
    """Response returned by POST /api/v1/recommendations/generate/{chain_id}."""
    success: bool = Field(default=True)
    recommendation_generated: bool = Field(default=True)
    chain_id: str = Field(...)
    data: Optional[RecommendationOutput] = Field(default=None)
    cached: bool = Field(default=False, description="True if retrieved from database cache")
    message: str = Field(default="Recommendation generated successfully")


class RecommendationBulkResponse(BaseModel):
    """Response returned when generating recommendations for all chains."""
    success: bool = Field(default=True)
    total_chains: int = Field(default=0)
    recommendations_generated: int = Field(default=0)
    cached_count: int = Field(default=0)
    execution_time_ms: float = Field(default=0.0)
    recommendations: List[RecommendationOutput] = Field(default_factory=list)
