import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import {
  Activity, AlertOctagon, AlertTriangle, ArrowLeft, ArrowUpRight, Bot, Check,
  ChevronRight, CircleHelp, Clock3, Command, Database, Download, FileUp, Filter,
  Flame, GitBranch, Globe2, Info, Layers3, Menu, MessageSquare, Network,
  PanelLeftClose, Play, Radar, RefreshCw, Search, Send, Shield, ShieldAlert,
  Sparkles, UploadCloud, Wifi, X, Zap
} from 'lucide-react';
import './styles.css';
import { api, getId, listFrom, severity } from './services/api';

function SeverityBadge({ value = 'unknown' }) {
  const label = value ? String(value) : 'Unknown';
  return <span className={`severity severity-${severity(value)}`}><span className="severity-dot" />{label}</span>;
}
function RiskScoreGauge({ score = 0 }) {
  const safe = Math.max(0, Math.min(100, Number(score) || 0));
  return <div className="gauge" style={{ '--score': `${safe * 3.6}deg` }}><div className="gauge-inner"><strong>{safe}</strong><span>/ 100</span></div></div>;
}
function MitreTechniqueChip({ technique = {} }) {
  const id = technique.technique_id || technique.id || technique.technique || '—';
  const name = technique.technique_name || technique.name || 'Unmapped';
  return <span className="mitre-chip"><span>{id}</span>{name}</span>;
}
function EmptyState({ icon: Icon = Database, title, text, action }) {
  return <div className="empty-state"><Icon size={24} /><h3>{title}</h3><p>{text}</p>{action}</div>;
}
function ErrorBanner({ message, onDismiss }) {
  if (!message) return null;
  return <div className="error-banner"><AlertTriangle size={16} /><span>{message}</span>{onDismiss && <button onClick={onDismiss}><X size={15} /></button>}</div>;
}
function Skeleton({ className = '' }) { return <div className={`skeleton ${className}`} />; }

function Sidebar({ page, setPage, collapsed, setCollapsed }) {
  const items = [
    ['upload', UploadCloud, 'Ingest'], ['dashboard', Network, 'Attack chains'],
    ['triage', Flame, 'Risk triage'], ['chat', MessageSquare, 'AI analyst']
  ];
  return <aside className={`sidebar ${collapsed ? 'collapsed' : ''}`}>
    <div className="brand"><div className="brand-mark"><Radar size={21} /></div><div className="brand-copy"><strong>SENTINEL<span>FORGE</span></strong><small>THREAT OPERATIONS</small></div><button className="collapse-btn" onClick={() => setCollapsed(!collapsed)}><PanelLeftClose size={17} /></button></div>
    <div className="mission-label">OPERATIONS CONSOLE</div>
    <nav>{items.map(([id, Icon, label]) => <button key={id} className={page === id ? 'active' : ''} onClick={() => setPage(id)}><Icon size={18} /><span>{label}</span>{page === id && <ChevronRight className="nav-arrow" size={14} />}</button>)}</nav>
    <div className="sidebar-bottom"><div className="system-pill"><span className="pulse" /> <span>Local API <b>connected</b></span></div><div className="operator"><div className="avatar">SO</div><div><strong>SOC Operator</strong><small>Level 03 · On duty</small></div><CircleHelp size={16} /></div></div>
  </aside>;
}
function Topbar({ title, eyebrow, setPage, onRefresh }) {
  return <header className="topbar"><div><div className="breadcrumb"><span>OPS CONSOLE</span><ChevronRight size={12} /><span>{eyebrow}</span></div><h1>{title}</h1></div><div className="topbar-actions"><div className="live-status"><span className="pulse" /> SYSTEM NOMINAL</div><button className="icon-btn" title="Refresh" onClick={onRefresh}><RefreshCw size={17} /></button><button className="icon-btn"><BellIcon /></button><button className="quick-btn" onClick={() => setPage('upload')}><FileUp size={16} /> Ingest alerts</button></div></header>;
}
function BellIcon() { return <span className="bell-icon">◉</span>; }

function UploadPage({ setPage }) {
  const [file, setFile] = useState(null); const [busy, setBusy] = useState(false); const [result, setResult] = useState(null); const [error, setError] = useState(''); const input = useRef();
  const onFile = f => { setError(''); setResult(null); if (!f) return; if (!f.name.toLowerCase().endsWith('.csv')) { setError('Rejected: only CSV files are accepted.'); return; } setFile(f); };
  const ingest = async () => { if (!file) return; setBusy(true); setError(''); try { const preview = await file.slice(0, 10000).text(); const headers = (preview.split(/\r?\n/)[0] || '').split(',').map(x => x.trim().replace(/^['"]|['"]$/g, '').toLowerCase()); const required = ['timestamp','src_ip','dst_ip','event','severity']; const missing = required.filter(x => !headers.includes(x)); if (missing.length) throw new Error(`Rejected: missing required column${missing.length > 1 ? 's' : ''}: ${missing.join(', ')}`); const form = new FormData(); form.append('file', file); setResult(await api('/api/v1/upload/ingest', { method: 'POST', body: form })); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <PageShell eyebrow="01 / INGEST" title="Alert ingestion" setPage={setPage}>
    <div className="hero-row"><div><p className="eyebrow cyan">SECURE DATA INTAKE</p><h2>Bring raw signals<br /><em>into focus.</em></h2><p className="lede">Upload a validated alert export to begin correlation. Sentinel Forge will normalize, group, and map events into attack chains.</p></div><div className="radar-art"><div className="radar-ring ring-one" /><div className="radar-ring ring-two" /><div className="radar-sweep" /><div className="radar-dot" /></div></div>
    <ErrorBanner message={error} onDismiss={() => setError('')} />
    {result ? <div className="success-panel"><div className="success-icon"><Check /></div><div><p className="eyebrow green">INGEST COMPLETE</p><h3>{result.alerts_ingested ?? result.count ?? result.ingested ?? 'Alerts'} alerts are ready</h3><p>Correlation can now generate attack chains from the ingested event set.</p></div><button className="primary-btn" onClick={() => setPage('dashboard')}>View attack chains <ArrowUpRight size={16} /></button></div> : <div className="upload-layout"><div className={`dropzone ${file ? 'has-file' : ''}`} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); onFile(e.dataTransfer.files[0]); }} onClick={() => input.current?.click()}><input ref={input} type="file" accept=".csv,text/csv" hidden onChange={e => onFile(e.target.files[0])} />{file ? <><div className="file-icon"><Check /></div><p className="drop-title">{file.name}</p><p className="drop-meta">{(file.size / 1024).toFixed(1)} KB · ready for validation</p><button className="text-btn" onClick={e => { e.stopPropagation(); setFile(null); }}>Choose another file</button></> : <><div className="upload-icon"><UploadCloud size={25} /></div><p className="drop-title">Drop your CSV here</p><p className="drop-meta">or click to browse from your workstation</p><span className="file-rule">CSV only · max file size enforced by API</span></>}</div><div className="ingest-side"><div className="panel-label"><Shield size={15} /> VALIDATION GATE</div><div className="validation-list">{['timestamp', 'src_ip', 'dst_ip', 'event', 'severity'].map(x => <div key={x}><Check size={15} /><code>{x}</code><span>required</span></div>)}</div><button className="primary-btn full" disabled={!file || busy} onClick={ingest}>{busy ? <><RefreshCw className="spin" size={16} /> Validating…</> : <><Zap size={16} /> Validate & ingest</>}</button><p className="microcopy"><Info size={13} /> Files are processed by the local FastAPI service.</p></div></div>}
    <div className="ingest-footer"><div><Database size={16} /><span>Pipeline ready</span></div><span>Accepted schema v1.0</span><span>POST /api/v1/upload/ingest</span></div>
  </PageShell>;
}

function PageShell({ children, title, eyebrow, setPage, onRefresh }) { return <><Topbar title={title} eyebrow={eyebrow} setPage={setPage} onRefresh={onRefresh} /><main className="content">{children}</main></>; }

function Dashboard({ setPage, onOpenChain }) {
  const [chains, setChains] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [filter, setFilter] = useState('all'); const [query, setQuery] = useState('');
  const load = () => { setLoading(true); api('/api/v1/chains/generate').then(d => setChains(listFrom(d, ['chains', 'data', 'results']))).catch(e => setError(e.message)).finally(() => setLoading(false)); }; useEffect(load, []);
  const visible = useMemo(() => chains.filter(c => filter === 'all' || severity(c.severity || c.risk_level) === filter).filter(c => !query || JSON.stringify(c).toLowerCase().includes(query.toLowerCase())), [chains, filter, query]);
  return <PageShell eyebrow="02 / CORRELATION" title="Attack chain dashboard" setPage={setPage} onRefresh={load}><div className="section-intro"><div><p className="eyebrow cyan">CORRELATED ACTIVITY</p><h2>Signal, connected.</h2><p className="lede">Review machine-correlated events and move from broad detection to a single, defensible narrative.</p></div><div className="metric-strip"><div><span>CHAINS DETECTED</span><strong>{loading ? '—' : chains.length}</strong></div><div><span>LAST SYNC</span><strong className="mono">{loading ? '—' : 'just now'}</strong></div></div></div><ErrorBanner message={error} onDismiss={() => setError('')} /><div className="toolbar"><div className="search-field"><Search size={16} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search chain ID, source IP…" /></div><div className="filter-group"><Filter size={15} /><span>Risk</span>{['all', 'critical', 'high', 'medium', 'low'].map(x => <button key={x} className={filter === x ? 'selected' : ''} onClick={() => setFilter(x)}>{x}</button>)}</div></div>{loading ? <div className="card-grid">{[1,2,3].map(i => <div className="chain-card" key={i}><Skeleton className="skeleton-line short" /><Skeleton className="skeleton-line" /><Skeleton className="skeleton-block" /></div>)}</div> : visible.length ? <div className="card-grid">{visible.map((c, i) => <ChainCard key={getId(c) || i} chain={c} onClick={() => onOpenChain(getId(c))} />)}</div> : <EmptyState icon={Network} title={chains.length ? 'No chains match this view' : 'No attack chains yet'} text={chains.length ? 'Try clearing the risk filter or search query.' : 'Ingest a CSV to generate correlated attack chains.'} action={!chains.length && <button className="secondary-btn" onClick={() => setPage('upload')}>Go to ingestion <ArrowUpRight size={15} /></button>} />}</PageShell>;
}
function ChainCard({ chain, onClick }) { const id = getId(chain) || '—'; const sev = chain.severity || chain.risk_level || chain.risk || 'Unknown'; const points = chain.events || chain.alerts || chain.records || []; return <button className="chain-card" onClick={onClick}><div className="card-top"><span className="chain-id">{id}</span><SeverityBadge value={sev} /></div><div className="chain-source"><Globe2 size={15} /><code>{chain.source_ip || chain.src_ip || 'Source unavailable'}</code></div>{points.length ? <div className="sparkline">{points.slice(0, 11).map((event, i) => <i key={i} style={{'--h': `${Math.min(96, 28 + ((Number(event.risk_score || event.score || event.severity_score) || (i + 2) * 7) % 69))}%`}} />)}</div> : <div className="sparkline-unavailable">Timeline data unavailable</div>}<div className="card-stats"><div><span>ALERTS</span><strong>{chain.alert_count ?? points.length ?? '—'}</strong></div><div><span>WINDOW</span><strong>{chain.start_time ? `${String(chain.start_time).slice(11, 16)} → ${String(chain.end_time || '').slice(11, 16)}` : '—'}</strong></div><ChevronRight size={18} /></div></button>; }

function Detail({ chainId, setPage, onBack }) {
  const [chain, setChain] = useState(null); const [mitre, setMitre] = useState(null); const [risk, setRisk] = useState(null); const [recommendations, setRecommendations] = useState(null); const [report, setReport] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!chainId) return; setLoading(true); Promise.all([api(`/api/v1/chains/${chainId}`), api(`/api/v1/mitre/map/${chainId}`), api(`/api/v1/risk/calculate/${chainId}`), api(`/api/v1/recommendations/${chainId}`).catch(() => null), api(`/api/v1/reports/${chainId}`).catch(() => null)]).then(([c,m,r,rec,rep]) => { setChain(c); setMitre(m); setRisk(r); setRecommendations(rec); setReport(rep); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [chainId]);
  if (loading) return <PageShell eyebrow="CHAIN DETAIL" title="Loading chain…" setPage={setPage}><div className="detail-skeleton"><Skeleton className="skeleton-block" /><Skeleton className="skeleton-block" /><Skeleton className="skeleton-block" /></div></PageShell>;
  const events = listFrom(chain, ['events', 'alerts', 'records']); const techniques = listFrom(mitre, ['techniques', 'mappings', 'data']); const score = risk?.final_score ?? risk?.risk_score ?? risk?.score ?? 0; const sev = risk?.severity || chain?.severity || 'Unknown';
  return <PageShell eyebrow="CHAIN DETAIL" title={chainId || 'Attack chain'} setPage={setPage}><button className="back-btn" onClick={onBack}><ArrowLeft size={15} /> Back to attack chains</button><ErrorBanner message={error} /><div className="detail-head"><div><p className="eyebrow cyan">CORRELATED INCIDENT</p><h2>{chainId}</h2><p className="lede">{chain?.source_ip || chain?.src_ip || 'Source IP unavailable'} <span className="dot-sep">·</span> {events.length || chain?.alert_count || 0} events <span className="dot-sep">·</span> {chain?.start_time || 'Time window unavailable'}</p></div><div className="score-card"><div><span className="eyebrow">RISK SCORE</span><SeverityBadge value={sev} /></div><RiskScoreGauge score={score} /></div></div><section className="detail-panel"><div className="panel-heading"><div><p className="eyebrow">EVENT SEQUENCE</p><h3>Kill-chain timeline</h3></div><span className="mono muted">{events.length} observed events</span></div><KillChainTimeline events={events} techniques={techniques} /></section><div className="detail-columns"><section className="detail-panel"><div className="panel-heading"><div><p className="eyebrow">SCORE COMPOSITION</p><h3>Risk breakdown</h3></div></div><div className="risk-breakdown">{[['Base event score', risk?.base_event_score], ['MITRE score', risk?.mitre_score], ['Kill-chain bonus', risk?.kill_chain_bonus], ['Final risk score', score]].map(([label,val], i) => <div key={label} className={i === 3 ? 'final' : ''}><span>{label}</span><strong>{val ?? '—'}</strong>{i < 3 && <div className="bar"><i style={{ width: `${Math.min(100, Number(val) || 0)}%` }} /></div>}</div>)}</div></section><Recommendations data={recommendations} /></div><div className="detail-actions"><button className="secondary-btn" onClick={() => setPage('workflow')}>View workflow status <ArrowUpRight size={15} /></button><button className="primary-btn" onClick={() => setPage('report')}>Open commander brief <ArrowUpRight size={15} /></button></div></PageShell>;
}
function KillChainTimeline({ events, techniques }) { const stages = ['Reconnaissance', 'Initial Access / Exploitation', 'Post-Exploitation']; return <div className="kill-chain">{stages.map((stage, i) => <div className="kill-stage" key={stage}><div className="stage-node">0{i + 1}</div><div className="stage-title">{stage}</div><div className="event-stack">{events.filter((e, idx) => i === 0 ? idx === 0 : i === 1 ? idx > 0 && idx < Math.ceil(events.length * .7) : idx >= Math.ceil(events.length * .7)).map((e, idx) => <div className="event-item" key={idx}><span className="event-time">{e.timestamp ? String(e.timestamp).slice(11,19) : '—'}</span><strong>{e.event || e.name || 'Observed event'}</strong><div>{techniques[idx] && <MitreTechniqueChip technique={techniques[idx]} />}</div></div>)}</div></div>)}</div>; }
function Recommendations({ data }) { const sections = [['Immediate Actions', 'immediate_actions'], ['Containment Actions', 'containment_actions'], ['Investigation Actions', 'investigation_actions'], ['Prevention Actions', 'prevention_actions']]; if (!data) return <section className="detail-panel"><div className="panel-heading"><div><p className="eyebrow">RESPONSE PLAYBOOK</p><h3>Recommendations</h3></div></div><EmptyState icon={Sparkles} title="Recommendations unavailable" text="The API did not return a response playbook for this chain." /></section>; return <section className="detail-panel"><div className="panel-heading"><div><p className="eyebrow">RESPONSE PLAYBOOK</p><h3>Recommendations</h3></div>{data.source && <span className="source-tag"><Sparkles size={13} /> {data.source}</span>}</div><div className="exec-summary"><span>EXECUTIVE SUMMARY</span><p>{data.executive_summary || data.summary || 'No executive summary supplied.'}</p></div><div className="recommend-grid">{sections.map(([label,key]) => <div key={key}><h4>{label}</h4><ul>{listFrom(data[key], ['items']).map((x,i) => <li key={i}>{typeof x === 'string' ? x : x.text || x.action || JSON.stringify(x)}</li>)}</ul></div>)}</div></section>; }

function Triage({ setPage, onOpenChain }) { const [data, setData] = useState([]); const [dist, setDist] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { Promise.all([api('/api/v1/risk/calculate-all'), api('/api/v1/risk/distribution')]).then(([all,d]) => { setData(listFrom(all, ['chains','results','data'])); setDist(d || {}); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []); const tiers = ['Critical','High','Medium','Low']; return <PageShell eyebrow="03 / PRIORITISATION" title="Risk triage" setPage={setPage}><div className="section-intro"><div><p className="eyebrow orange">COMMAND PRIORITY</p><h2>Put risk in order.</h2><p className="lede">A global view of the incidents that need human attention first.</p></div></div><ErrorBanner message={error} /><div className="triage-top"><div className="distribution-panel"><div className="panel-heading"><div><p className="eyebrow">THREAT DISTRIBUTION</p><h3>Current exposure</h3></div><Activity size={18} /></div><div className="distribution-bars">{tiers.map(t => { const val = dist[t.toLowerCase()] ?? dist[t] ?? dist[`${t.toLowerCase()}_count`] ?? 0; const total = tiers.reduce((a,x) => a + Number(dist[x.toLowerCase()] ?? dist[x] ?? 0), 0) || 1; return <div className={`dist-row ${severity(t)}`} key={t}><span><i />{t}</span><div className="dist-bar"><i style={{width: `${Math.min(100, Number(val)/total*100)}%`}} /></div><strong>{val}</strong></div>; })}</div></div><div className="triage-callout"><Flame size={21} /><span>ANALYST NOTE</span><h3>Prioritise high-confidence<br />chains with active motion.</h3><p>Risk scores combine event severity, MITRE context, and kill-chain progression.</p></div></div><div className="detail-panel table-panel"><div className="panel-heading"><div><p className="eyebrow">RANKED CHAINS</p><h3>All active priorities</h3></div><span className="mono muted">{data.length} chains</span></div>{loading ? <div className="table-loading"><Skeleton /><Skeleton /><Skeleton /></div> : data.length ? <div className="table-wrap"><table><thead><tr><th>RANK</th><th>CHAIN</th><th>SOURCE</th><th>RISK</th><th>SEVERITY</th><th>LAST OBSERVED</th><th /></tr></thead><tbody>{data.map((c,i) => <tr key={getId(c)||i} onClick={() => onOpenChain(getId(c))}><td><span className="rank">{String(i+1).padStart(2,'0')}</span></td><td><code>{getId(c)||'—'}</code></td><td><code>{c.source_ip || c.src_ip || '—'}</code></td><td><strong className="risk-number">{c.final_score ?? c.risk_score ?? c.score ?? '—'}</strong></td><td><SeverityBadge value={c.severity || c.risk_level || 'Unknown'} /></td><td className="mono muted">{c.end_time || c.timestamp || '—'}</td><td><ChevronRight size={16} /></td></tr>)}</tbody></table></div> : <EmptyState icon={Flame} title="Nothing to triage" text="Risk rankings will appear after chains have been ingested and scored." />}</div></PageShell>; }

function Report({ chainId, setPage }) { const [report,setReport] = useState(null); const [error,setError] = useState(''); useEffect(() => { if (chainId) api(`/api/v1/reports/${chainId}`).then(setReport).catch(e=>setError(e.message)); }, [chainId]); return <PageShell eyebrow="COMMAND BRIEF" title="Executive BLUF" setPage={setPage}><div className="report-toolbar"><button className="back-btn" onClick={() => setPage('dashboard')}><ArrowLeft size={15} /> Back</button><button className="secondary-btn" onClick={() => window.print()}><Download size={15} /> Print / export</button></div><ErrorBanner message={error} />{report ? <article className="report-page"><div className="report-kicker">SENTINEL FORGE / COMMANDER BRIEF <span>{chainId}</span></div><ThreatLevelBanner value={report.threat_level || report.severity || 'Unknown'} /><ReportSection title="Executive Summary" value={report.executive_summary || report.summary} /><ReportSection title="Attack Overview" value={report.attack_overview || report.overview} /><ReportSection title="Affected Assets" value={report.affected_assets || report.assets} /><ReportSection title="MITRE Summary" value={report.mitre_summary || report.mitre} /><ReportSection title="Recommended Actions" value={report.recommended_actions || report.actions} /><ReportSection title="Conclusion" value={report.conclusion} /></article> : <div className="detail-skeleton"><Skeleton className="skeleton-block" /><Skeleton className="skeleton-block" /></div>}</PageShell>; }
function ThreatLevelBanner({ value }) { return <div className={`threat-banner ${severity(value)}`}><div><span className="eyebrow">THREAT LEVEL</span><strong>{value}</strong></div><AlertOctagon size={54} /></div>; }
function ReportSection({ title, value }) { return <section className="report-section"><h3>{title}</h3><div>{Array.isArray(value) ? <ul>{value.map((x,i)=><li key={i}>{typeof x==='string'?x:JSON.stringify(x)}</li>)}</ul> : <p>{value || 'No data supplied by the report service.'}</p>}</div></section>; }

function Workflow({ chainId, setPage }) { const [status,setStatus] = useState(null); const [busy,setBusy] = useState(false); const [error,setError] = useState(''); const steps=['Load Chain','MITRE','Risk','Recommendations','BLUF','Store']; const load=()=>chainId&&api(`/api/v1/workflow/status/${chainId}`).then(setStatus).catch(e=>setError(e.message)); useEffect(load,[chainId]); const run=async path=>{setBusy(true);setError('');try{await api(path,{method:'POST'});await load();}catch(e){setError(e.message)}finally{setBusy(false)}}; return <PageShell eyebrow="04 / ORCHESTRATION" title="Workflow status" setPage={setPage}><div className="section-intro"><div><p className="eyebrow cyan">PIPELINE CONTROL</p><h2>Know what ran.</h2><p className="lede">Observe each enrichment stage, rerun the workflow, and surface short-circuits before they become blind spots.</p></div><div className="workflow-actions"><button className="secondary-btn" disabled={!chainId||busy} onClick={()=>run(`/api/v1/workflow/run/${chainId}`)}><Play size={15}/> Run chain</button><button className="primary-btn" disabled={busy} onClick={()=>run('/api/v1/workflow/run-all')}><Zap size={15}/> Run all</button></div></div><ErrorBanner message={error} /><div className="workflow-panel">{chainId ? <><div className="workflow-meta"><span>CHAIN <code>{chainId}</code></span><span className="muted">{status?.status || 'Awaiting status'}</span></div><div className="stepper">{steps.map((step,i)=>{const item=status?.steps?.[i] || status?.[step.toLowerCase()] || {}; const state=typeof item==='string'?item:item.status||item.state||'pending'; return <div className={`step ${severity(state)}`} key={step}><div className="step-dot">{state==='completed'||state==='success'?<Check size={14}/>:i+1}</div><strong>{step}</strong><span>{state}</span>{i<steps.length-1&&<div className="step-line"/>}</div>})}</div><div className="workflow-note"><Info size={16}/><span>Failures and short-circuits from the API are surfaced inline. A completed stage is not rerun unless the workflow endpoint requests it.</span></div></> : <EmptyState icon={GitBranch} title="Select a chain to inspect its workflow" text="Open a chain detail view first, then return here to watch orchestration progress." action={<button className="secondary-btn" onClick={()=>setPage('dashboard')}>Browse chains <ArrowUpRight size={15}/></button>} />}</div></PageShell>; }

function Chat({ setPage }) { const [session,setSession]=useState(null); const [messages,setMessages]=useState([]); const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); useEffect(()=>{api('/api/v1/chat/new-session',{method:'POST'}).then(d=>setSession(d.session_id||d.id||d)).catch(e=>setError(e.message));},[]); useEffect(()=>{if(session?.session_id||typeof session==='string'){const id=session.session_id||session;api(`/api/v1/chat/history/${id}`).then(d=>setMessages(listFrom(d,['messages','history','data']))).catch(()=>{});}},[session]); const send=async e=>{e.preventDefault();if(!input.trim()||busy||!session)return;const text=input;setInput('');setMessages(m=>[...m,{role:'user',content:text,message:text}]);setBusy(true);try{const d=await api('/api/v1/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:session.session_id||session,message:text,query:text})});setMessages(m=>[...m,d]);}catch(e){setError(e.message)}finally{setBusy(false)}}; return <PageShell eyebrow="05 / ANALYST DESK" title="AI analyst" setPage={setPage}><div className="chat-layout"><div className="chat-header"><div><p className="eyebrow cyan">SECURE ANALYST CHANNEL</p><h2>Ask the intelligence layer.</h2><p className="lede">Query correlated chains, risk context, and MITRE mappings in plain language.</p></div><div className="session-chip"><span className="pulse" /> SESSION {session?.session_id || session || 'INITIALISING'}</div></div><ErrorBanner message={error} /><div className="chat-window"><div className="chat-scroll">{messages.length ? messages.map((m,i)=><ChatMessage key={i} message={m}/>) : <div className="chat-empty"><Bot size={28}/><h3>Analyst channel is ready</h3><p>Ask about an attack chain, source IP, technique, or prioritisation decision.</p></div>}{busy&&<div className="chat-bubble ai"><div className="typing"><i/><i/><i/></div></div>}</div><form className="chat-form" onSubmit={send}><span className="terminal-prompt">›</span><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask the analyst…" /><button className="primary-btn" disabled={busy||!input.trim()}><Send size={16}/></button></form></div></div></PageShell>; }
function ChatMessage({message}) { const role=message.role||message.sender||'assistant'; const text=message.content||message.message||message.text||''; const noData=text.includes('No matching threat intelligence records'); return <div className={`chat-bubble ${role==='user'?'user':'ai'} ${noData?'no-data':''}`}>{role!=='user'&&<div className="ai-label"><Bot size={14}/> SENTINEL ANALYST</div>}{noData?<><div className="neutral-state"><Info size={17}/><span>{text}</span></div></>:role==='user'?<p>{text}</p>:<div className="structured-answer"><AnswerBlock title="Threat Summary" text={text} /><AnswerBlock title="Risk Assessment" text={text} /><AnswerBlock title="Relevant MITRE Techniques" text={text} /><AnswerBlock title="Recommended Actions" text={text} /></div>}</div>; }
function AnswerBlock({title,text}) { const lower=title.toLowerCase(); const parts=text.split(/\n+/).filter(Boolean); const relevant=parts.filter(x=>x.toLowerCase().includes(lower.split(' ')[0])||x.includes(':')); return <div><span>{title}</span><p>{relevant.length ? relevant.join(' ') : text}</p></div>; }

function App() { const [page,setPage]=useState('upload'); const [collapsed,setCollapsed]=useState(false); const [selected,setSelected]=useState(null); const openChain=id=>{setSelected(id);setPage('detail')}; const pageContent=page==='upload'?<UploadPage setPage={setPage}/>:page==='dashboard'?<Dashboard setPage={setPage} onOpenChain={openChain}/>:page==='detail'?<Detail chainId={selected} setPage={setPage} onBack={()=>setPage('dashboard')}/>:page==='triage'?<Triage setPage={setPage} onOpenChain={openChain}/>:page==='report'?<Report chainId={selected} setPage={setPage}/>:page==='workflow'?<Workflow chainId={selected} setPage={setPage}/>:<Chat setPage={setPage}/>; return <div className="app-shell"><Sidebar page={page} setPage={setPage} collapsed={collapsed} setCollapsed={setCollapsed}/><div className="main-shell">{pageContent}</div></div>; }

createRoot(document.getElementById('root')).render(<App />);
